#!/bin/sh
xrandr --output eDP1 --off --output DP1 --off --output DP2 --off --output DP2-1 --off --output DP2-2 --primary --mode 1920x1200 --pos 1600x0 --rotate normal --output DP2-3 --off --output HDMI1 --mode 1600x1200 --pos 0x0 --rotate normal --output HDMI2 --off --output VIRTUAL1 --off
