#!/bin/sh
ACTION=$1
if [ ! "$ACTION" ]; then
	ACTION="hd"
	echo "Depricated - pls define action"
	echo "available: <hd>, <arch>"
fi

if [ "$ACTION" == "hd" ]; then
	PICPATH="$HOME/Bilder/HD/"
	RANGE=21
elif [ "$ACTION" == "arch" ]; then
	RANGE=25
	PICPATH="$HOME/Bilder/arch/bild"
else
	echo 
	#TODO
fi

number=$RANDOM
let "number %= $RANGE"
#echo $PICPATH$number".jpg"
feh --bg-scale $PICPATH$number".jpg"
