#!/bin/sh

# Parameters
group=$1
location=$2

# Config
set -u
set -b
#set -n # developing mode

# Statics
AVAILABLE_GROUPS=(default privat work) # Only used for help
SCRIPT_DIR=$HOME/.bin/scripts/setup/
NM_COMMAND_SET="nmcli con up uuid"

# Main Method
main() {
	case $group in
		default	| d)
			setup_default
			;;
		priv | privat | p)
			group=priv
			local P_LOCALTIONS=(hihome)
			;;
		arbeit | a | work)
			group=arbeit
			local P_LOCALTIONS=(sse rz)
			;;
		*)
			echo "Invalid group. Available groups: ${AVAILABLE_GROUPS[@]}"
			exit 1
			;;
	esac
	containsElement "$location" "${P_LOCALTIONS[@]}"
	if [[ "$?" -eq "1" ]]; then
		echo "> Starting setup for $location"
		setup_"$group"_"$location"
	else
		# location is not in P_LOCATION
		echo "Invalid location. Available location in "$group": ${P_LOCALTIONS[@]}" 
	fi
}

function containsElement {
	local e match="$1"
	shift
	for e; do [[ "$e" == "$match" ]] && return 1; done
	return 0
}

function setup_priv_hihome {
	echo ">> running monitor setup..."
	$SCRIPT_DIR/hi-home.screenlayout
	echo ">> running networksetup via networkmanager..."
	`$NM_COMMAND_SET 585bc297-c19d-30ce-a344-a26e32bc6034`
	echo ">> running i3 setup..."
	$SCRIPT_DIR/hi-home.i3script
}
function setup_arbeit_rz {
	echo ">> running networksetup via networkmanager..."
	nmcli con up uuid "e8ca4590-af96-4d4e-8c15-4e144b789998"
	echo ">> running monitor setup..."
	$SCRIPT_DIR/hi-arbeit.screenlayout
	echo ">> running i3 setup..."
	$SCRIPT_DIR/hi-arbeit.i3script
}
function setup_arbeit_sse {
	echo ">> running networksetup via networkmanager..."
	nmcli con up uuid "9e588387-345b-4763-9ac9-005e5b7b9187"
	echo ">> running monitor setup..."
	$SCRIPT_DIR/arbeit-sse.screenlayout
	#echo ">> running i3 setup..."
	#$SCRIPT_DIR/arbeit-sse.i3script
	i3-msg restart
}
function setup_default {
	echo "> Starting default setup"
	echo ">> running monitor setup..."
	$HOME/.screenlayout/default.sh
	echo ">> restart i3"
	i3-msg restart
}


##Start##
main
##Start##
